In [132]:
#installation
!pip install numpy

In [133]:
#creating numpy arrays
import numpy as np

In [134]:
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [135]:
#shape
array1.shape

(5,)

In [136]:
#dim
array1.ndim

1

In [137]:
#size
array1.size

5

In [138]:
#itemsize
array1.itemsize

8

In [139]:
#dtype
array1.dtype

dtype('int64')

In [140]:
#astype
array1.astype("float")

array([1., 2., 3., 4., 5.])

In [141]:
array2 = np.array([[1, 2, 3], [4, 5, 6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
#shape
array2.shape

(2, 3)

In [143]:
#dim
array2.ndim

2

In [144]:
#size
array2.size

6

In [145]:
#itemsize
array2.itemsize

8

In [146]:
#dtype
array2.dtype

dtype('int64')

In [147]:
#astype
array2.astype("float")

array([[1., 2., 3.],
       [4., 5., 6.]])

#Numpy Array vs Python List

##Numpy array are faster, convinient and occupys less memory

In [148]:
list_a = range(100)
list_a

range(0, 100)

In [149]:
array_a = np.arange(100)
array_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [150]:
import sys

In [151]:
print(sys.getsizeof(87)*len(list_a))

2800


In [152]:
print(array_a.itemsize*array_a.size)

800


from this we can see that numpy takes less space

In [153]:
import time

In [154]:
x=range(100000)
y=range(100000,200000)

#time function gives current time
start_time=time.time()

#It selects element from both array add them and puts the sum in another list
c=[(x+y) for x,y in zip(x,y)]
print(time.time()-start_time)

0.008963346481323242


In [155]:
y=np.arange(100000)
x=np.arange(100000,200000)

#Now for performing same operation as above in numpy
start_time=time.time()
c=x+y

time.time()-start_time

0.0023305416107177734

from this we can see that numpy is faster then python

#Indexing, Slicing and Iteration

In [156]:
array3 = np.arange(24)
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [157]:
#change the shape of an array
array4 = np.arange(24).reshape(6, 4)
array4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

np.arange(n).reshape(r, c) => n = r * c

In [158]:
#rows
print(array4[0:3])
print("-------------")
print(array4[2:5])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------
[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array[r, c] => in r => array[start, end]

In [159]:
#columns
print(array4[:, 0:2])
print("-----------")
print(array4[:, 1:3])

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]]
-----------
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]


In [160]:
array4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [161]:
#to get specific pies of matrics
print(array4[2:4, 1:3])

[[ 9 10]
 [13 14]]


#Operations in Numpy

In [162]:
array5 = np.array([1, 2, 3, 4, 5])
array6 = np.array([6, 7, 8, 9, 10])

In [163]:
array5 + array6

array([ 7,  9, 11, 13, 15])

In [164]:
array5 - array6

array([-5, -5, -5, -5, -5])

In [165]:
array5 * array6

array([ 6, 14, 24, 36, 50])

In [166]:
(array5 * 2) - (array6 * 4)

array([-22, -24, -26, -28, -30])

In [167]:
array5 > 3

array([False, False, False,  True,  True])

In [168]:
array6 < 7

array([ True, False, False, False, False])

In [169]:
array_x = np.arange(6).reshape(2,3)
array_y = np.arange(6,12).reshape(3,2)

#For matrix multiplication
array_x.dot(array_y)

array([[ 28,  31],
       [100, 112]])

In [170]:
array7 = np.arange(35).reshape(5, 7)
array7

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [171]:
#to find max in matrics
array7.max()

np.int64(34)

In [172]:
#to find min in matrics
array7.min()

np.int64(0)

In [173]:
#to find max column wise
array7.max(axis=0)

array([28, 29, 30, 31, 32, 33, 34])

In [174]:
#to find min column wise
array7.min(axis=0)

array([0, 1, 2, 3, 4, 5, 6])

In [175]:
#to find max row wise
array7.max(axis=1)

array([ 6, 13, 20, 27, 34])

In [176]:
#to find min row wise
array7.min(axis=1)

array([ 0,  7, 14, 21, 28])

In [177]:
#cal mean median std of array
print(array7.mean())
print(np.median(array7))
print(array7.std())

17.0
17.0
10.099504938362077


In [ ]:
np.sin(array7)

In [ ]:
np.cos(array7)

In [ ]:
np.exp(array7)

In [181]:
array8 = np.array([-1, -2, -3])
array8

array([-1, -2, -3])

In [182]:
np.abs(array8)

array([1, 2, 3])

In [183]:
array9 = np.arange(45).reshape(5, 9)
array9

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [184]:
#to flatten to 1d array
array9.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [185]:
array9

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [186]:
array9.transpose()

array([[ 0,  9, 18, 27, 36],
       [ 1, 10, 19, 28, 37],
       [ 2, 11, 20, 29, 38],
       [ 3, 12, 21, 30, 39],
       [ 4, 13, 22, 31, 40],
       [ 5, 14, 23, 32, 41],
       [ 6, 15, 24, 33, 42],
       [ 7, 16, 25, 34, 43],
       [ 8, 17, 26, 35, 44]])

In [187]:
array9.trace()

np.int64(100)

In [188]:
array10 = np.array([[1, 2, 3], [4, 5, 6]])
array11 = np.array([[7, 8, 9], [10, 11, 12]])

In [189]:
array10

array([[1, 2, 3],
       [4, 5, 6]])

In [190]:
array11

array([[ 7,  8,  9],
       [10, 11, 12]])

In [191]:
# to stack/combine horizontally, to stack vertically use vstack
print(np.hstack((array10, array11)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [192]:
print(np.vstack((array10, array11)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#Indexing with boolean arrays

In [193]:
#to get random integer in a range with given no of size
array12 = np.random.randint(low=1, high=10, size=15).reshape(5, 3)
array12

array([[8, 9, 5],
       [5, 8, 8],
       [5, 1, 3],
       [1, 8, 2],
       [8, 9, 5]])

In [194]:
array12 > 5

array([[ True,  True, False],
       [False,  True,  True],
       [False, False, False],
       [False,  True, False],
       [ True,  True, False]])

In [195]:
array12 < 6

array([[False, False,  True],
       [ True, False, False],
       [ True,  True,  True],
       [ True, False,  True],
       [False, False,  True]])

In [196]:
#to get array containing elements which are greater then 5, also know as indexing using boolean array
array12[array12 > 5]

array([8, 9, 8, 8, 8, 8, 9])

In [197]:
array12[array12 < 6]

array([5, 5, 5, 1, 3, 1, 2, 5])

In [198]:
#to get elements which are greter then 5 and even
array12[((array12 > 5) & (array12%2 == 0))]

array([8, 8, 8, 8, 8])

In [199]:
#to get elements which are grether then 5 or even
array12[((array12 > 5) | (array12%2 == 0))]

array([8, 9, 8, 8, 8, 2, 8, 9])

#Plotting Graph in Numpy

In [ ]:
array13 = np.linspace(-50, 50, 100)
array13

In [201]:
x = array13

In [202]:
x.size

100

In [ ]:
y = np.sin(x)
y

In [204]:
import matplotlib.pyplot as plt

#this line is used to print graph on screeen without it graph will not appear
%matplotlib inline

In [ ]:
plt.plot(x, y)

In [ ]:
z = np.cos(x)
z

In [ ]:
plt.plot(x, z)

#Broadcasting in numpy

Broadcasting means numpy automatically adjust arrays shapes so math operations works without for-loops

In [208]:
array14 = np.array([1, 2, 3])
array14

array([1, 2, 3])

In [209]:
array14 + 10

array([11, 12, 13])

In [210]:
array15 = np.array([4, 5, 6])
array14 + array15

array([5, 7, 9])

In [211]:
matrix = np.array([[1, 2, 3],[4, 5, 6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [212]:
matrix.ndim

2

In [213]:
row = np.array([7, 8, 9])
row

array([7, 8, 9])

In [214]:
row.ndim

1

In [215]:
matrix + row

array([[ 8, 10, 12],
       [11, 13, 15]])

In [216]:
col = np.array([[1],
                [2],
                [3]])
col

array([[1],
       [2],
       [3]])

In [217]:
row = np.array([10, 20])
row

array([10, 20])

In [218]:
col.ndim

2

In [219]:
row.ndim

1

In [220]:
col + row

array([[11, 21],
       [12, 22],
       [13, 23]])

Shapes not compatible

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20])

a + b

#some important function in numpy

In [222]:
#to get random values bw 0 and 1
np.random.random()

0.35653172355805496

In [223]:
#to get same value again and again
np.random.seed(1)
np.random.random()

0.417022004702574

In [224]:
#to get random value in given range
np.random.uniform(2, 3)

2.720324493442158

In [ ]:
#to get random values array in range with in given size
np.random.uniform(1, 2, 20).reshape(4, 5)

In [226]:
#to get random integer in given range
np.random.randint(1, 100)

64

In [227]:
i = np.random.randint(1, 50, 15).reshape(3, 5)
i

array([[23,  2,  1, 18,  9],
       [25, 14, 48, 43,  9],
       [31,  8,  4,  7, 22]])

In [228]:
np.max(i)

np.int64(48)

In [229]:
#to get largest elements index in array
np.argmax(i)

np.int64(7)

In [230]:
np.min(i)

np.int64(1)

In [231]:
#to get smallest elements index in array
np.argmin(i)

np.int64(2)