In [ ]:
#installation
!pip install numpy

In [2]:
#creating numpy arrays
import numpy as np

In [5]:
#creating 1D array
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [6]:
#check datatype of array
type(array1)

numpy.ndarray

In [7]:
#check dim of ndarray
array1.ndim

1

In [8]:
#creating 2D array
array2 = np.array([[1, 2, 3], [4, 5, 6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#check dim of ndarray
array2.ndim

2

In [10]:
#Creates matrix of given order with all elements as zeros
zeroes = np.zeros([2, 3])
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

np.zeros([r, c])

In [11]:
##Creates matrix of given order with all elements as ones
ones = np.ones([3, 2])
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

np.ones([r, c])

In [12]:
#create identity metrics of order n
n = int(input("order = "))
identity = np.identity(n)
identity

order = 5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
#Creates elements of given range in function contains of 3 parameter
# 1st and 2nd paramter is for range and third parameter is for jump check line 16
array3 = np.arange(15)
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

np.arange(start, end, jump)

In [14]:
array4 = np.arange(5, 15)
array4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
array5 = np.arange(5, 15, 2)
array5

array([ 5,  7,  9, 11, 13])

start: inclusive
end: non-inclusive

In [18]:
#creates evenly spaced numbers between two values
array6 = np.linspace(0, 10, 5)
array6

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

np.linspace(start, stop, num)
start: starting value
stop: ending value
num: how many numbers wants(including starting & ending)

In [19]:
#copies an array
array7 = array6.copy()
array7

array([ 0. ,  2.5,  5. ,  7.5, 10. ])